@startuml
class Lokasyon{
 ' https://support.google.com/maps/answer/18539?co=GENIE.Platform%3DDesktop&hl=en
  - double x
  - double y
}
Motorcu -> Lokasyon
class Motorcu{
  - string isim
  ..
  - Lokasyon konum
  ..
  - bool bosda
  ..
  -
  ==
  End of class
}
Main "1" ---> "*" Motorcu
class Main{
  - list<Motorcu> motorcular
  ==
  + JSON get_motorcular()
}
@enduml